#drop database crisp;
#delete from donation_request;
#alter table donation_request auto_increment = 1;
#select * from donation_request;

INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(1,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(2,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(3,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(4,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(5,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(6,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(7,'Please accept me','Accepted','approved');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(8,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(9,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(10,'Please accept me','Dead','rejected');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(9,'Please accept me','Accepted','approved');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(8,'Please accept me','Dead','rejected');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(7,'Please accept me','Accepted','approved');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(6,'Please accept me','','pending');
INSERT INTO donation_request(person_id,donor_remarks,admin_remarks,status) VALUES(5,'Please accept me','Not Eligible','rejected');